{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a279be4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================\n",
    "# 🏦 Bank Customer Churn Prediction - train.py\n",
    "# ==========================================\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pickle\n",
    "import os\n",
    "from sklearn.model_selection import train_test_split, GridSearchCV\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report\n",
    "from xgboost import XGBClassifier\n",
    "\n",
    "# ------------------------------------------\n",
    "# 1️⃣ Load the cleaned dataset\n",
    "# ------------------------------------------\n",
    "DATA_PATH = \"data/cleaned_bank_churn.csv\"\n",
    "df = pd.read_csv(DATA_PATH)\n",
    "\n",
    "print(f\"✅ Loaded dataset with {df.shape[0]} rows and {df.shape[1]} columns\")\n",
    "\n",
    "# ------------------------------------------\n",
    "# 2️⃣ Prepare features and target\n",
    "# ------------------------------------------\n",
    "X = df.drop('churn', axis=1)\n",
    "y = df['churn']\n",
    "\n",
    "# ------------------------------------------\n",
    "# 3️⃣ Scale numeric features\n",
    "# ------------------------------------------\n",
    "scaler = StandardScaler()\n",
    "X_scaled = scaler.fit_transform(X)\n",
    "\n",
    "# Split into train/test\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X_scaled, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "\n",
    "# ------------------------------------------\n",
    "# 4️⃣ Train XGBoost Classifier (Final Model)\n",
    "# ------------------------------------------\n",
    "print(\"\\n🚀 Training XGBoost model...\")\n",
    "\n",
    "xgb_clf = XGBClassifier(\n",
    "    eval_metric='logloss',\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "# Optional tuning - comment out if already tuned\n",
    "param_grid = {\n",
    "    'n_estimators': [200],\n",
    "    'max_depth': [5],\n",
    "    'learning_rate': [0.05],\n",
    "    'subsample': [0.8]\n",
    "}\n",
    "\n",
    "grid = GridSearchCV(xgb_clf, param_grid, cv=3, scoring='f1', n_jobs=-1, verbose=1)\n",
    "grid.fit(X_train, y_train)\n",
    "\n",
    "best_model = grid.best_estimator_\n",
    "print(\"\\n✅ Best model parameters:\", grid.best_params_)\n",
    "\n",
    "# ------------------------------------------\n",
    "# 5️⃣ Evaluate the final model\n",
    "# ------------------------------------------\n",
    "y_pred = best_model.predict(X_test)\n",
    "print(\"\\n📊 Model Evaluation:\")\n",
    "print(\"Accuracy:\", accuracy_score(y_test, y_pred))\n",
    "print(\"F1 Score:\", f1_score(y_test, y_pred))\n",
    "print(\"ROC-AUC:\", roc_auc_score(y_test, best_model.predict_proba(X_test)[:, 1]))\n",
    "print(\"\\nClassification Report:\\n\", classification_report(y_test, y_pred))\n",
    "\n",
    "# ------------------------------------------\n",
    "# 6️⃣ Save model and scaler\n",
    "# ------------------------------------------\n",
    "os.makedirs(\"models\", exist_ok=True)\n",
    "\n",
    "pickle.dump(best_model, open(\"models/model.pkl\", \"wb\"))\n",
    "pickle.dump(scaler, open(\"models/scaler.pkl\", \"wb\"))\n",
    "\n",
    "print(\"\\n💾 Model and scaler saved successfully in /models folder!\")\n",
    "print(\"✅ Training completed.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
